spring:
  application:
    name: GeoLocation
  datasource:
    url: jdbc:mysql://m21-database-server.mysql.database.azure.com:3306/address_api_db?allowPublicKeyRetrieval=true&useSSL=false
    username: m21admin
    password: Troy@2019
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
